# Generated by Django 3.0.3 on 2020-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneritem',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/banneritem'),
        ),
    ]
